### ISSUE TITLE
backbonejs & underscorejs

### ISSUE THREAD

**Issue by DmitryBochkarev** [1602/makedoc#1]
http://github.com/documentcloud/backbone
https://github.com/documentcloud/underscore

Данные библиотеки хорошо документированы, но парсер совершенно не видит документации.
Было бы замечательно, если бы инструмент понимал и такой формат, отличный от javadoc.

**Comment by 1602** [comment]
В общем-то такой формат понятен парсеру, здесь проблема в отступах, потому что однострочные комментарии с ненулевым отступом считаются недокументирующими в настоящий момент. Плюс для подобных библиотек, когда все в одном файле надо в целом пересмотреть генерацию файлов документации.

**Comment by DmitryBochkarev** [comment]
Понятно, тогда стоит пока оставить этот вопрос. Лучше написать хороший инструмент, который справляется со своей задачей. Нужна какая-нибудь помощь?
