### ISSUE TITLE
nothing generated for class with no method or class name is one letter

### ISSUE THREAD

**Issue by tyt2y3** [1602/makedoc#3]
sorry, but I installed makedoc and run it through a sample file:

``` javascript
/**
 * Class A
 * @constructor
 * @param {Object} a
 */
function A(a) {
    var x=0;
}
```

and outputs:

```
what: function A(a) 
what: {
what: var x=0;
what: }
./dropped_exper/test.js 0 0 0
path.existsSync is now called `fs.existsSync`.
writing readme: index.html
```

then only the barebone is in index.html
thx

**Comment by anatoliychakkaev** [comment]
Hahah! Congratulations, you've spotted edge case.

It doesn't works when:

1) class has no methods
2) class name is just one letter

So, this code is parseable:

```
/**
 * Class Abrakazabra
 * @constructor
 * @param {Object} a
 */
function Abrakadabra(a) {
    var x=0;
}

Abrakadabra.prototype.b = function () {
};
```

But this one is not:

```
/**
 * Class Abrakadabra
 * @constructor
 * @param {Object} a
 */
function Abrakadabra(a) {
    var x=0;
}
```

And this one too:

```
/**
 * Class A
 * @constructor
 * @param {Object} a
 */
function A(a) {
    var x=0;
}
```

---

I have mixed feelings about it. From the one point of view: this is bug. But from another: who need to describe classes with no methods? And why need to name classes with a single letters?

**Comment by tyt2y3** [comment]
thank you for your explanation!
you are right about the one-lettered-no-method class, they have no use.
Just feeling wired.
